//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBXHealthGenerator.AgentConfigurationService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AgentConfigurationService.IAgentConfigurationService")]
    public interface IAgentConfigurationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgentConfigurationService/reportHealth", ReplyAction="http://tempuri.org/IAgentConfigurationService/reportHealthResponse")]
        string reportHealth(string agentConfiguration);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAgentConfigurationServiceChannel : WBXHealthGenerator.AgentConfigurationService.IAgentConfigurationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AgentConfigurationServiceClient : System.ServiceModel.ClientBase<WBXHealthGenerator.AgentConfigurationService.IAgentConfigurationService>, WBXHealthGenerator.AgentConfigurationService.IAgentConfigurationService {
        
        public AgentConfigurationServiceClient() {
        }
        
        public AgentConfigurationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AgentConfigurationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AgentConfigurationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AgentConfigurationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string reportHealth(string agentConfiguration) {
            return base.Channel.reportHealth(agentConfiguration);
        }
    }
}
