//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBXEventGenerator.EventCollectorService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EventCollectorService.IEventCollectorService")]
    public interface IEventCollectorService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEventCollectorService/reportEvent", ReplyAction="http://tempuri.org/IEventCollectorService/reportEventResponse")]
        void reportEvent(string Event);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEventCollectorService/reportEvents", ReplyAction="http://tempuri.org/IEventCollectorService/reportEventsResponse")]
        void reportEvents(string Events);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEventCollectorServiceChannel : WBXEventGenerator.EventCollectorService.IEventCollectorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EventCollectorServiceClient : System.ServiceModel.ClientBase<WBXEventGenerator.EventCollectorService.IEventCollectorService>, WBXEventGenerator.EventCollectorService.IEventCollectorService {
        
        public EventCollectorServiceClient() {
        }
        
        public EventCollectorServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EventCollectorServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EventCollectorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EventCollectorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void reportEvent(string Event) {
            base.Channel.reportEvent(Event);
        }
        
        public void reportEvents(string Events) {
            base.Channel.reportEvents(Events);
        }
    }
}
